baseURL = "https://totallynotdavid.github.io/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# enableRobotsTXT = true
languageCode = "es-ES"

[minify]
  disableJs = false
  [minify.tdewolff]
  [minify.tdewolff.html]
    keepWhitespace = false
  [minify.tdewolff.js]
    # https://github.com/tdewolff/minify/issues/472
    keepVarNames = true
    noNullishOperator = false
    precision = 0