[[social]]
  name = "Twitter"
  url = "https://twitter.com/totallynotdavid"
  weight = 10

[[social]]
  name = "Linkedin"
  url = "https://www.linkedin.com/in/amosduran/"
  weight = 20

[[social]]
  name = "Instagram"
  url = "https://www.instagram.com/terriblephysicist/"
  weight = 20