# Meta Data for SEO

## Homepage
title = "David's Portfolio"
description = "Condensed matter, condensed code"
small_description = "I'm an Undergraduate Physics student interested in Computational and Condensed Matter Physics."

## Chrome Browser
themeColor = "#fff"

[options]
  darkMode = true
  breadCrumb = true
  highLight = true
  kaTex = true